### ISSUE TITLE
[Refactor] Menu descriptions are not being created correctly.

### ISSUE THREAD

**Issue by ashcorpdev** [ShrineFox/Persona-5-Mod-Menu#42]
It appears as though the menu descriptions are not being created/compiled correctly. See screenshot below:

![P5R_aCxbECcVEc](https://github.com/ShrineFox/Persona-5-Mod-Menu/assets/5949532/bfcc5422-d1c7-45db-974f-4982a21a1b4f)

It seems to be pulling descriptions from the in-game menus rather than the custom ones in the `.msg` files.

![P5R_oDH9Yu5iCt](https://github.com/ShrineFox/Persona-5-Mod-Menu/assets/5949532/8ba0c727-7200-47fd-bb23-094f0832c9f0)

**Comment by ShrineFox** [comment]
You're right, it looks like I forgot to mention this in the readme or the wiki, so I should go update that. But it's the intended behavior unless you run the program with the ``-r`` argument (or check the "reindex" box if using the GUI).

The reason for this is due to a strange quirk with how the game handles the menu description text.
For menu options, the markup that looks like ``[ref 9 10]`` has two integer values.
The first is the index of the option in the menu, and the second is the index of the message in the compiled script.

The latter can change due to messages being added, removed, or compiled in a different order, making it unfeasible to update these by hand. Different versions of the game also have a different number of messages in the original scripts, making it even harder to predict accurately what these numbers end up being.

Recompiling with the reindex argument compiles and then decompiles the script, checks the index of each message and then updates the values before compiling again to ensure that they're accurate. This process is rather slow, so I have it off by default to allow for quicker debugging.

Thing is, this process could be made more efficient if I could predict the order in which scripts are compiled. That way I would only have to count the number of messages in the script being hooked, but I never quite figured it out so I opted for this hacky method. If this were implemented, I could make reindexing the default behavior without much of an efficiency tradeoff

**Comment by ashcorpdev** [comment]
Thanks for the explanation!

I did try running with the re-indexing option enabled a few times, but still ended up with the same result. Looking at the output console, a few errors popped up relating to AtlusScriptCompiler attempting to re-compile some of the `.bf.flow` files (not sure if that's expected or not). 

```
[01/17/2024 09:21 AM]   args: "H:\Reloaded II\Mods\p5rpc.modmenu.2\P5REssentials\CPK\EN.CPK\FIELD\ETC\at_dng.bf" -Decompile -Encoding P5R_EFIGS -Library P5R
17/01/2024 09:21:35  Info: Using P5R_EFIGS encoding
17/01/2024 09:21:35  Info: Output file path is set to H:\Reloaded II\Mods\p5rpc.modmenu.2\P5REssentials\CPK\EN.CPK\FIELD\ETC\at_dng.bf.flow
17/01/2024 09:21:35  Error: Binary files can't be compiled again!
17/01/2024 09:21:35  Error: One or more errors occured while executing task!
```

---

Regarding what you mentioned with the way the re-indexing works by updating the values - I also noticed that the AtlusScriptCompiler complains when some of the `GENERIC_HELP_` messages have the same names when re-indexing. 

Do these need to be unique? I have a test branch currently where I've re-named all the `GENERIC_HELP` messages to unique names across the entirety of the `.msg` files, but the re-indexing still doesn't seem to work. My assumption that this is because I renamed them to something along the lines of `GENERIC_HELP_MENU_1` instead of `GENERIC_HELP_1` and the ModMenuBuilder is expecting only numbers there?

```cs
if (msgLines[i].Contains("[dlg GENERIC_HELP_"))
     msgLines[i] = $"[dlg GENERIC_HELP_{index}]";
 ```

Looking at the older versions of the menu where the descriptions were working, I'm assuming you had indexed them all into the hundreds (e.g., `GENERIC_HELP_334`) to ensure that they were unique, even before re-indexing.

**Comment by ShrineFox** [comment]
Thanks, your comments pointed me in the right direction! Debugging was a bit of a doozy, for some reason, it wouldn't re-parse arguments and assumed I was compiling despite using the Decompile argument, so I explicitly specify the mode based on input file format now.  
It was also failing to reindex messages because it found more than one match using ``msgs.Single``, so I changed it to ``msgs.First`` and it seems to work now. I had to enable "Just My Code" in Visual Studio in order to even see the error message. Hopefully all is good now!

**Comment by ashcorpdev** [comment]
Sorry about the delay in getting back to you - got caught up in some of my own projects. Looks like your fixes resolved the issue - I can see descriptions as expected after re-indexing, so I will close the issue for now. If I spot anything else awry, I'll re-open if needed.
